# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploghubapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='rank',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='rank',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='net_votes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='upvotes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='net_votes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=1),
        ),
    ]
