# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 11:39
from __future__ import unicode_literals

from django.db import migrations

def create_user_profile(apps, schema_editor):
    UserProfile = apps.get_model("ploghubapp", "UserProfile")
    User = apps.get_model("auth", "User")
    for user in User.objects.all():
        user_profile = UserProfile(user=user, about="(empty)")
        user_profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ploghubapp', '0003_historicaluserprofile_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_user_profile),
    ]
