# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ploghubapp', '0008_historicalvotecomment_votecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvotecomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='votecomment',
            name='post',
        ),
        migrations.AddField(
            model_name='historicalvotecomment',
            name='comment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ploghubapp.Comment'),
        ),
        migrations.AddField(
            model_name='votecomment',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ploghubapp.Comment'),
            preserve_default=False,
        ),
    ]
