# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploghubapp', '0009_auto_20170813_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='comment_karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='submission_karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comment_karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='submission_karma',
            field=models.IntegerField(default=0),
        ),
    ]
