# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploghubapp', '0010_auto_20170814_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='net_votes',
            field=models.IntegerField(default=0),
        ),
    ]
